language: node_js
node_js:  
  - "7"

os:
  - linux
  - osx


env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

git:
  depth: 5

before_install:
install:
  - npm install -g node-gyp
  - npm install
script: 
  - npm test

branches:
  only:
    - refactor-with-test-spec