language: node_js
node_js:  
  - "7"

os:
  - linux
  - osx


env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

matrix:
  exclude:
  - os: osx
  - env: CXX=g++-4.8

git:
  depth: 5

before_install:
  - npm install -g node-gyp

install:
  - npm install

  
script: 
  - npm test

branches:
  only:
    - refactor-with-test-spec