language: node_js
node_js:  
  - "7"

os:
  - linux
  - osx

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

matrix:
  include:
    - os: osx
      env: CXX=clang
  exclude:
    - os: osx
      env: CXX=g++-4.8

git:
  depth: 5


install:
  - npm install -g node-gyp
  - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script: 
  - npm test
  - npm run e2e
  
branches:
  only:
    - master