language: node_js
node_js:  
  - "7"

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

matrix:
  include:
    - os: osx
      env: CXX=clang
    - os: linux
      evn: CXX=g++-4.8

git:
  depth: 5


install:
  - npm install -g node-gyp
  - npm install


script: 
  - npm test

branches:
  only:
    - refactor-with-test-spec